apiVersion: v1
kind: Service
metadata:
  name: locplace
  namespace: locplace
spec:
  selector:
    app: locplace
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: "http"
  type: ClusterIP
  