apiVersion: v1
kind: Service
metadata:
  name: locplace
  namespace: locplace
  labels:
    app: locplace
spec:
  selector:
    app: locplace
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: "http"
    - name: "metrics"
      protocol: TCP
      port: 9090
      targetPort: "metrics"
  type: ClusterIP
